version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: login-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  app:
    depends_on:
      - mongodb
    build: .
    container_name: login-api
    restart: always
    ports:
      - 3000:3000
